### PR TITLE
Update all modules exports to features 2.5. This module had someone o…

### PR DESCRIPTION
**Pull request by frankcarey**
…verriding the features with functions. This should happen in an alter or this component should not be exported as a feature.

### CODE REVIEW

**Comment by frankcarey** [comment]
This should be in the Features META issue https://github.com/NuCivic/dkan/issues/467

**Comment by teosibileau** [comment]
@frankcarey we can't get this in as it is. That feed importer started as a feature, but then @acouch and @msolv added those functions in order to make the datastore work with content types other than dkan_dataset resources.

That clearly shouldn't be a feature anymore, we need to add that feed importer on install for dkan_datastore using something like:

```
$importer = feeds_importer($importer->id);
$importer->setConfig($importer->config);
foreach (array('fetcher', 'parser', 'processor') as $type) {
  $importer->$type->setConfig($importer->config[$type]['config']);
}
$importer->save();
```

**Comment by teosibileau** [comment]
@frankcarey getting this in as it is for now while i'm working on removing the feed importers feature

**Comment by tenken** [comment]
Hi. I was looking at DKAN over the last few days because we're moving a legacy site into drupal and it contains alot of historical data and essentially datasets. I could really use dkan_datastore in this project. I found these directions to tie it to my own drupal project:
https://github.com/NuCivic/dkan_datastore#using-without-dkan

But, after implementing those hook functions, the Feeds imported bundled via Features is still hardcoded to a "dataset" content type and a "resource" field.

So for my needs I overrode these values for my needs and the module works fine outside of DKAN. I recommend updating directions in the README to detail how datastore should be implemented outside of DKAN if that will still (hopefully) be supported after https://github.com/NuCivic/dkan/issues/517.

Thanks for great tools and workflows you guys support in your distribution.

**Pull request merged**
